spring:
  # log color 출력
  output:
    ansi:
      enabled: always
  # H2 데이터 베이스 설정
  h2:
    console:
      enabled: true
  # JDBC 설정
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  # JPA 설정
  jpa :
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true